name: rl-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python版本
  - python=3.10

  # 深度学习框架（GPU版本 - RTX 5070 + CUDA 12.8）
  # 注意：RTX 5070需要PyTorch nightly版本
  # 手动安装：pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
  - pytorch-cuda=12.4  # 占位符，实际使用nightly版本

  # 基础科学计算
  - numpy=1.26.0
  - scipy>=1.10.0
  - pandas>=2.2.0

  # 可视化
  - matplotlib>=3.7.0
  - seaborn>=0.12.0

  # Jupyter（用于notebook开发）
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - ipywidgets>=8.0.0
  - jupyterlab>=4.0.0

  # 开发工具
  - black
  - flake8
  - isort
  - pytest

  # 使用pip安装的包
  - pip
  - pip:
      # RL环境（核心）
      - gymnasium==1.2.0
      - shimmy>=2.0.0
      
      # 游戏和渲染
      - pygame>=2.5.0
      - opencv-python==4.11.0.86
      - imageio>=2.31.0
      
      # 日志和实验追踪
      - tensorboard==2.20.0
      - tqdm==4.67.1
      
      # RL算法库（参考实现）
      - stable-baselines3==2.7.0
      
      # 配置管理
      - pyyaml>=6.0
      - hydra-core>=1.3.0
      - omegaconf>=2.3.0

